### ISSUE TITLE
slide misalignment

### ISSUE THREAD

**Issue by charleshross** [viniciusalmeida/ninja-presentation#11]
When you load the page with "http://localhost:9090/ninja-presentation/" instead of "http://localhost:9090/ninja-presentation/#1", the slide goes mis-aligned. It auto-corrects if you change the browser's width. I'm running in the latest Chrome.

http://i.imgur.com/Yx4qcEJ.png

**Comment by viniciusalmeida** [comment]
@charleshross the problem persists? i think this is fixed on PR #15
