### ISSUE TITLE
slide name requires a dash

### ISSUE THREAD

**Issue by driewieler-digital** [viniciusalmeida/ninja-presentation#12]
From http://www.html5rocks.com/en/tutorials/webcomponents/customelements/

The first argument to document.registerElement() is the element's tag name. The name must contain a dash (-). So for example, <x-tags>, <my-element>, and <my-awesome-app> are all valid names, while <tabs> and <foo_bar> are not. This restriction allows the parser to distinguish custom elements from regular elements but also ensures forward compatibility when new tags are added to HTML.

Change this:

< polymer-element name='slide' attributes='background font color align' >

to this:

< polymer-element name='ninja-slide' attributes='background font color align' >

plzktnx

**Comment by viniciusalmeida** [comment]
Fixed at https://github.com/viniciusalmeida/ninja-presentation/issues/15
