### ISSUE TITLE
Demos appear to be horribly broken on latest Chrome

### ISSUE THREAD

**Issue by benmccormick** [viniciusalmeida/ninja-presentation#13]
I came upon this project today, and decided to check out the demos linked in the README.

Not sure if it's due to Chrome updates or Polymer updates, but the demos are both in very bad shape visiting them from Chrome 36 on OSX.

https://www.evernote.com/shard/s55/sh/a7ff8c39-053d-4110-bb8d-259ab52b805b/49f8198523a3eb61ab09d47f7e1bf20b/deep/0/Talk-GruntJS-and-Main-Window.png

Just thought you'd want to know.

**Comment by ghost** [comment]
same on windows and chrome

**Comment by viniciusalmeida** [comment]
This error is pertinent on the repo of demo presentations (https://github.com/viniciusalmeida/presentations)
