### ISSUE TITLE
Not working with firefox developer

### ISSUE THREAD

**Issue by victorperin** [viniciusalmeida/ninja-presentation#19]
The styles, like left align, background, etc. isn't working on firefox developer edition 39.0a2 (2015-05-11).
Probably also not working on all others firefox browsers.

**Comment by viniciusalmeida** [comment]
You are correct @victorperin, the `ninja-presentation` really works only in Google Chrome.

I think that something of Polymer broke the component at Mozilla Firefox but the project are a experiment and fix him it's not in my plans for now. If you can fix that i really would appreciate your collaboration.

**Comment by victorperin** [comment]
I'll try, sorry for lefting it at this way, i'm not having so much time.

Also, i didn't thanks for your work. It's really useful!

**Comment by viniciusalmeida** [comment]
Thanks man. Enjoy it!
