### ISSUE TITLE
Maintain only gh-pages branch

### ISSUE THREAD

**Issue by zenorocha** [viniciusalmeida/ninja-presentation#3]
Here's a little advice I've been doing on my custom elements repos.

There's no need for maintaining a `master` branch, so if you want to avoid merging every single commit to `gh-pages`, just make it as the default branch.
1. Go ahead and make `gh-pages` as the default one
   
   ![](http://zno.io/R2gS/change-branch.gif)
2. Then remove `master` local and remote branches.
   
   ```
   git push branch -D master
   ```
   
   ```
   git push origin :master
   ```

**Comment by viniciusalmeida** [comment]
good tip. thanks
