### ISSUE TITLE
See the demo

### ISSUE THREAD

**Issue by emanuelespies** [viniciusalmeida/ninja-presentation#4]
See the demo didn't open to me.
Appears a 404 error.

;*

**Comment by viniciusalmeida** [comment]
Today the tool name has changed. now is 'ninja-presentation' to follow a pattern of a repository named [customelements.io](http://customelements.io/).
The links are wrong on moment, but i go fix that soon.
You can view the tool working here [ninja-presentation demo](http://viniciusalmeida.github.io/ninja-presentation/)
While it are not fix, that issue keeps open.

Thankx Manu!

**Comment by viniciusalmeida** [comment]
it's all right :)
