### ISSUE TITLE
Bower integration

### ISSUE THREAD

**Issue by matiasleidemer** [viniciusalmeida/ninja-presentation#5]
How about creating a public package for ninja-presentation using [Bower](http://bower.io/)? You could even remove that nasty polymer include from the instructions and add it as a dependency.

[Here](http://simplesideias.com.br/gerenciando-dependencias-client-side-com-bower) are some portuguese instructions for bower.

**Comment by viniciusalmeida** [comment]
Well i think it are finished.
Try `$ bower intall ninja-presentation` ;)

Thanks by tip @matiasleidemer.
